In [5]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics 
from sklearn.metrics import accuracy_score

data1 = pd.read_csv(r'D:/cv_final_project/z/Bull.csv',header=None,dtype='uint8')
data1=data1.astype(np.uint8) 

data2 = pd.read_csv(r'D:/cv_final_project/z/Cattle.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8) 

data3 = pd.read_csv(r'D:/cv_final_project/z/Elephant.csv',header=None,dtype='uint8')
data3=data3.astype(np.uint8) 

data4 = pd.read_csv(r'D:/cv_final_project/z/Horse.csv',header=None,dtype='uint8')
data4=data4.astype(np.uint8) 

data5 = pd.read_csv(r'D:/cv_final_project/z/Leopard.csv',header=None,dtype='uint8')
data5=data5.astype(np.uint8) 

data6 = pd.read_csv(r'D:/cv_final_project/z/Monkey.csv',header=None,dtype='uint8')
data6=data6.astype(np.uint8) 

data7 = pd.read_csv(r'D:/cv_final_project/z/Pig.csv',header=None,dtype='uint8')
data7=data7.astype(np.uint8)

data8 = pd.read_csv(r'D:/cv_final_project/z/Rabbit.csv',header=None,dtype='uint8')
data8=data8.astype(np.uint8) 

data9 = pd.read_csv(r'D:/cv_final_project/z/Sheep.csv',header=None,dtype='uint8')
data9=data9.astype(np.uint8) 

In [8]:
#For data1
kmeans_data1 = KMeans(n_clusters=17, n_init=10)
kmeans_data1.fit(data1)

#For data2
kmeans_data2 = KMeans(n_clusters=17, n_init=10)
kmeans_data2.fit(data2)

#For data3
kmeans_data3 = KMeans(n_clusters=17, n_init=10)
kmeans_data3.fit(data3)

#For data4
kmeans_data4 = KMeans(n_clusters=17, n_init=10)
kmeans_data4.fit(data4)

#For data5
kmeans_data5 = KMeans(n_clusters=17, n_init=10)
kmeans_data5.fit(data5)

#For data6
kmeans_data6 = KMeans(n_clusters=17, n_init=10)
kmeans_data6.fit(data6)

#For data7
kmeans_data7 = KMeans(n_clusters=17, n_init=10)
kmeans_data7.fit(data7)

#For data8
kmeans_data8 = KMeans(n_clusters=17, n_init=10)
kmeans_data8.fit(data8)

#For data8
kmeans_data9 = KMeans(n_clusters=17, n_init=10)
kmeans_data9.fit(data9)

KMeans(n_clusters=17, n_init=10)

In [9]:
import pickle
# Save the model to disk for data 1
filename_data1 = 'Kmeans_CL_5_Model_data1.sav'
with open(filename_data1, 'wb') as file:
    pickle.dump(kmeans_data1, file)
    
# Save the model to disk for data2
filename_data2 = 'Kmeans_CL_5_Model_data2.sav'
with open(filename_data2, 'wb') as file:
    pickle.dump(kmeans_data2, file)
    
# Save the model to disk for data2
filename_data3 = 'Kmeans_CL_5_Model_data3.sav'
with open(filename_data3, 'wb') as file:
    pickle.dump(kmeans_data3, file)
    
# Save the model to disk for data2
filename_data4 = 'Kmeans_CL_5_Model_data4.sav'
with open(filename_data4, 'wb') as file:
    pickle.dump(kmeans_data4, file)
    
filename_data5 = 'Kmeans_CL_5_Model_data5.sav'
with open(filename_data5, 'wb') as file:
    pickle.dump(kmeans_data5, file)

filename_data6 = 'Kmeans_CL_5_Model_data6.sav'
with open(filename_data6, 'wb') as file:
    pickle.dump(kmeans_data6, file)
    
filename_data7 = 'Kmeans_CL_5_Model_data7.sav'
with open(filename_data7, 'wb') as file:
    pickle.dump(kmeans_data7, file)
    
filename_data8 = 'Kmeans_CL_5_Model_data8.sav'
with open(filename_data8, 'wb') as file:
    pickle.dump(kmeans_data8, file)

filename_data9 = 'Kmeans_CL_5_Model_data9.sav'
with open(filename_data9, 'wb') as file:
    pickle.dump(kmeans_data9, file)

print('complete')

complete


In [11]:

# Compute histogram of trained Kmeans of data1
hist_data1 = np.histogram(kmeans_data1.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data1:')
print(hist_data1, "\n")

# Compute histogram of trained Kmeans of data1
hist_data2 = np.histogram(kmeans_data2.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data2:')
print(hist_data2, "\n")

# Compute histogram of trained Kmeans of data1
hist_data3 = np.histogram(kmeans_data3.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data3:')
print(hist_data3, "\n")

# Compute histogram of trained Kmeans of data1
hist_data4 = np.histogram(kmeans_data4.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data4:')
print(hist_data4, "\n")

# Compute histogram of trained Kmeans of data1
hist_data5 = np.histogram(kmeans_data5.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data5:')
print(hist_data5, "\n")

# Compute histogram of trained Kmeans of data1
hist_data6 = np.histogram(kmeans_data6.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data6:')
print(hist_data6, "\n")

# Compute histogram of trained Kmeans of data1
hist_data7 = np.histogram(kmeans_data7.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data7:')
print(hist_data7, "\n")

# Compute histogram of trained Kmeans of data1
hist_data8 = np.histogram(kmeans_data8.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data8:')
print(hist_data8, "\n")

# Compute histogram of trained Kmeans of data1
hist_data9 = np.histogram(kmeans_data9.labels_, bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
print('Histogram of trained kmeans for data9:')
print(hist_data9, "\n")

Histogram of trained kmeans for data1:
(array([1781, 2187, 2140, 1903, 1754, 2061, 2134, 2268, 1677, 1972, 2022,
       1935,    0, 4231, 1989, 1880, 2344], dtype=int64), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 12, 14, 15, 16,
       17])) 

Histogram of trained kmeans for data2:
(array([2794, 2613, 2415, 2708, 2726, 3293, 2323, 2190, 1976, 1955, 2627,
       2672,    0, 5753, 2127, 2535, 2940], dtype=int64), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 12, 14, 15, 16,
       17])) 

Histogram of trained kmeans for data3:
(array([ 8068,  6131,  8127,  7395,  7024,  6124,  6442,  6607,  6496,
        6515,  7485,  8307,     0, 16384,  7797,  7716,  8312],
      dtype=int64), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 12, 14, 15, 16,
       17])) 

Histogram of trained kmeans for data4:
(array([11260, 15750, 14562, 18295, 13449, 14323, 14893, 16691, 17148,
       14759, 15273, 19201,     0, 32806, 15834, 14993, 11325],
      dtype=int64), 

In [15]:
import os
import csv
import cv2
import matplotlib.pyplot as plt
folder1=r"D:/mine/train/Bull"
folder2=r"D:/mine/train/Cattle"
folder3=r"D:/mine/train/Elephant"
folder4=r"D:/mine/train/Horse"
folder5=r"D:/mine/train/Leopard"
folder6=r"D:/mine/train/Monkey"
folder7=r"D:/mine/train/Pig"
folder8=r"D:/mine/train/Rabbit"
folder9=r"D:/mine/train/Sheep"

#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path 
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data1.predict(array_double)
    
    hist_data1=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data1[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output1 = pd.DataFrame(data)
#add row class 
Output1["Class"] = 1 
csv_data=Output1.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset1.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [17]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder2):
    #path 
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data2.predict(array_double)
    
    hist_data2=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data2[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output2 = pd.DataFrame(data)
#add row class 
Output2["Class"] = 2
csv_data=Output2.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset2.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [18]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder3):
    #path 
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data3.predict(array_double)
    
    hist_data3=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data3[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output3 = pd.DataFrame(data)
#add row class 
Output3["Class"] = 3
csv_data=Output3.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset3.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [19]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder4):
    #path 
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data4.predict(array_double)
    
    hist_data4=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data4[0])
    #k=k+1

Output4 = pd.DataFrame(data)
Output4["Class"] = 4
csv_data=Output4.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset4.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [20]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder5):
    #path 
    path=os.path.join(folder5,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data5.predict(array_double)
    
    hist_data5=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data5[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output5 = pd.DataFrame(data)
#add row class 
Output5["Class"] = 5
csv_data=Output5.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset5.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [21]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder6):
    #path 
    path=os.path.join(folder6,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data6.predict(array_double)
    
    hist_data6=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data6[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output6 = pd.DataFrame(data)
#add row class 
Output6["Class"] = 6
csv_data=Output6.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset6.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [22]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder7):
    #path 
    path=os.path.join(folder7,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data7.predict(array_double)
    
    hist_data7=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data7[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output7 = pd.DataFrame(data)
#add row class 
Output7["Class"] = 7
csv_data=Output7.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset7.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [23]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder8):
    #path 
    path=os.path.join(folder8,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data8.predict(array_double)
    
    hist_data8=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data8[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output8 = pd.DataFrame(data)
#add row class 
Output8["Class"] = 8
csv_data=Output8.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset8.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [25]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder9):
    #path 
    path=os.path.join(folder9,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data9.predict(array_double)
    
    hist_data9=np.histogram(a,bins=[0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,12,14,15,16,17])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data9[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output9 = pd.DataFrame(data)
#add row class 
Output9["Class"] = 9
csv_data=Output1.to_csv(r'D:/cv_final_project\z\17kmeans\Dataset9.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [26]:
print("Bull")
print(Output1)

Bull
     0    1    2    3    4    5    6    7    8    9   10   11  12   13   14  \
0   15    5   36   16   20    9   22   13   16   19   21    7   0   28   21   
1   53   60   55   60   22   28   48   58   30   23   41   31   0  121   19   
2   37   39   22   41   48   29   54   44   39   76   38   78   0   99   63   
3   37   34   64   83   45   29   51   53   47   42   60   47   0  150   31   
4   31   46   30   35   31   55   47   34   26   50   54   75   0   91   58   
5   44   41   34   12   28   22   33   77   47   17   35   50   0   75   21   
6   35   37   54   43   30   61   57   85   34   32   40   32   0  100   69   
7   49   38   63   45   42   45   60   28   41   40   49   36   0   87   57   
8   39   40   46   64   25   17   28   42   28   40   18   20   0   90   20   
9   35  160   34   11   60   72   55   92   35   76   51   64   0   83   52   
10   8   11    3    0    4   38   18    7    4    7   11    5   0   13   25   
11   9    6    8    0    8   33    7   23    6 

In [27]:
A = pd.concat([Output1, Output2, Output3,Output4,Output5,Output6,Output7,Output8,Output9], ignore_index=True)
A

0    1   2   3    4   5    6    7   8   9  10  11  12   13  14  15  16  \
0     15    5  36  16   20   9   22   13  16  19  21   7   0   28  21  10  28   
1     53   60  55  60   22  28   48   58  30  23  41  31   0  121  19  32  36   
2     37   39  22  41   48  29   54   44  39  76  38  78   0   99  63  45  34   
3     37   34  64  83   45  29   51   53  47  42  60  47   0  150  31  53  86   
4     31   46  30  35   31  55   47   34  26  50  54  75   0   91  58  38  25   
...   ..  ...  ..  ..  ...  ..  ...  ...  ..  ..  ..  ..  ..  ...  ..  ..  ..   
2064  43   25  71  92   29  27   27   18  94  71  74  79   0  125  29  24  77   
2065  35   33  20  53  106  42   52   41  57  22  29  44   0   85  16  33  43   
2066  30   43  13  57   42  46   34   39  61  36   6  51   0   55  39  40  43   
2067  71  103  19  46  181  87  112  104  37  30  28  68   0  181  55  48  68   
2068  49   68  80  70   28  72   39   51  86  85  57  81   0   82  33  56  75   

      Class  
0         1  
1         1  
2         1  
3         1  
4         1  
...     ...  
2064      9  
2065      9  
2066      9  
2067      9  
2068      9  

[2069 rows x 18 columns]

In [28]:
csv_data=A.to_csv(r'D:/cv_final_project\z\17kmeans\Final_SIFT\FinalSIFT.csv', mode='a',header=False,index=False)


In [29]:
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, f1_score

In [30]:
Data_SIFT=A
Data_SIFT
df = pd.DataFrame(Data_SIFT)
print("Completed")

Completed


In [31]:
csv_data=df.to_csv(r'D:/cv_final_project\z\17kmeans\Final_SIFT\FinalFusedSIFT.csv', mode='a',header=False,index=False)

In [6]:
reduced_features = pd.read_csv(r'D:/cv_final_project\z\17kmeans\Final_SIFT\FinalFusedSIFT.csv',header=None)
reduced_features

0    1   2   3    4   5    6    7   8   9   10  11  12   13  14  15  16  \
0     15    5  36  16   20   9   22   13  16  19  21   7   0   28  21  10  28   
1     53   60  55  60   22  28   48   58  30  23  41  31   0  121  19  32  36   
2     37   39  22  41   48  29   54   44  39  76  38  78   0   99  63  45  34   
3     37   34  64  83   45  29   51   53  47  42  60  47   0  150  31  53  86   
4     31   46  30  35   31  55   47   34  26  50  54  75   0   91  58  38  25   
...   ..  ...  ..  ..  ...  ..  ...  ...  ..  ..  ..  ..  ..  ...  ..  ..  ..   
2064  43   25  71  92   29  27   27   18  94  71  74  79   0  125  29  24  77   
2065  35   33  20  53  106  42   52   41  57  22  29  44   0   85  16  33  43   
2066  30   43  13  57   42  46   34   39  61  36   6  51   0   55  39  40  43   
2067  71  103  19  46  181  87  112  104  37  30  28  68   0  181  55  48  68   
2068  49   68  80  70   28  72   39   51  86  85  57  81   0   82  33  56  75   

      17  
0      1  
1      1  
2      1  
3      1  
4      1  
...   ..  
2064   9  
2065   9  
2066   9  
2067   9  
2068   9  

[2069 rows x 18 columns]

In [7]:
reduced_features.isnull().values.any()
X = reduced_features.drop(columns= 17, axis=1)
Y = reduced_features[17]

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.2, random_state = 0)
# describes info about train and test set
print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", Y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", Y_test.shape)

Number transactions X_train dataset:  (1655, 17)
Number transactions y_train dataset:  (1655,)
Number transactions X_test dataset:  (414, 17)
Number transactions y_test dataset:  (414,)


In [15]:
from sklearn.linear_model import LogisticRegression

# Create a Logistic Regression classifier
modelLR = LogisticRegression(max_iter=1000, random_state=42)
modelLR.fit(X_train, Y_train)


# Accuracy on training data
X_train_prediction = modelLR.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Train data: ', train_data_accuracy)
print('Precision:', precision_score(X_train_prediction, Y_train, average='weighted'))
print('Recall:', recall_score(X_train_prediction, Y_train, average='weighted'))
print('F1 score:', f1_score(X_train_prediction, Y_train, average='weighted'))
train_confusion_matrix = confusion_matrix(X_train_prediction, Y_train)
print("Confusion Matrix for Training Data:")
print(train_confusion_matrix)



# Accuracy on test data
X_test_prediction = modelLR.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test data: ', test_data_accuracy)
print('Precision:', precision_score(X_test_prediction, Y_test, average='weighted'))
print('Recall:', recall_score(X_test_prediction, Y_test, average='weighted'))
print('F1 score:', f1_score(X_test_prediction, Y_test, average='weighted'))
test_confusion_matrix = confusion_matrix(X_test_prediction, Y_test)
print("\nConfusion Matrix for Testing Data:")
print(test_confusion_matrix)

Accuracy on Train data:  0.5709969788519638
Precision: 0.7162623152732953
Recall: 0.5709969788519638
F1 score: 0.6219015636835777
Confusion Matrix for Training Data:
[[  0   0   0   0   0   0   2   0   0]
 [  0   5   2   1   1   1   3   2   0]
 [  2   1  32  11   4   7   1   2  12]
 [ 17   2  21 225  14  28  40  27  21]
 [  1   1  11   5  47   6   6   2   2]
 [ 13  40  43  65  22 555  45  86  28]
 [  0   2   4   9   4  16  43  11   8]
 [  1   4   8   5   9   3   9  30   8]
 [  0   3   1   1   0   0   3   3   8]]

Accuracy on Test data:  0.5507246376811594
Precision: 0.695181375959408
Recall: 0.5507246376811594
F1 score: 0.6026263750144251

Confusion Matrix for Testing Data:
[[  0   0   0   0   0   0   0   0   0]
 [  0   0   3   0   0   0   1   0   0]
 [  1   1  12   6   2   2   2   2   0]
 [  5   3   4  48   4   7   9  11   2]
 [  1   0   1   1  10   4   0   0   0]
 [  4   6  11  17   4 138   8  34   4]
 [  1   0   0   1   1   3  13   0   2]
 [  1   0   2   5   1   0   5   4   1]
 [  0

C:\Users\parth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\parth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create a Decision Tree Classifier
modelDT = DecisionTreeClassifier(max_depth=9)

# Train the model on the training data
modelDT.fit(X_train, Y_train)

# Predict on the training data
X_train_prediction = modelDT.predict(X_train)

# Calculate accuracy on training data
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training Data: ', train_data_accuracy)

# Calculate precision on training data
train_data_precision = precision_score(X_train_prediction, Y_train, average='weighted')
print('Precision on Training Data: ', train_data_precision)

# Calculate recall on training data
train_data_recall = recall_score(X_train_prediction, Y_train, average='weighted')
print('Recall on Training Data: ', train_data_recall)

# Calculate F1 score on training data
train_data_f1_score = f1_score(X_train_prediction, Y_train, average='weighted')
print('F1 Score on Training Data: ', train_data_f1_score)

# Generate a confusion matrix for training data
confusion_matrix_train = confusion_matrix(Y_train, X_train_prediction)
print('Confusion Matrix (Training Data):\n', confusion_matrix_train)

# Predict on the test data
X_test_prediction = modelDT.predict(X_test)

# Calculate accuracy on test data
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test Data: ', test_data_accuracy)

# Calculate precision on test data
test_data_precision = precision_score(X_test_prediction, Y_test, average='weighted')
print('Precision on Test Data: ', test_data_precision)

# Calculate recall on test data
test_data_recall = recall_score(X_test_prediction, Y_test, average='weighted')
print('Recall on Test Data: ', test_data_recall)

# Calculate F1 score on test data
test_data_f1_score = f1_score(X_test_prediction, Y_test, average='weighted')
print('F1 Score on Test Data: ', test_data_f1_score)

# Generate a confusion matrix for test data
confusion_matrix_test = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix (Test Data):\n', confusion_matrix_test)


Accuracy on Training Data:  0.8459214501510574
Precision on Training Data:  0.8572258250771057
Recall on Training Data:  0.8459214501510574
F1 Score on Training Data:  0.8489906915108125
Confusion Matrix (Training Data):
 [[ 23   0   1   7   0   1   0   1   1]
 [  0  37   1   2   2  13   2   0   1]
 [  2   0  91   4   4  13   4   0   4]
 [  0   2   5 289   4  12   7   0   3]
 [  2   2   2   3  77   9   6   0   0]
 [  2   2   4   8   1 584  11   2   2]
 [  1   1   1  14   2   9 121   1   2]
 [  0   1   4   5   3  10   8 131   1]
 [  0   2   4   5   3  17   8   1  47]]

Accuracy on Test Data:  0.6014492753623188
Precision on Test Data:  0.6224193215039897
Recall on Test Data:  0.6014492753623188
F1 Score on Test Data:  0.6084417006875994
Confusion Matrix (Test Data):
 [[  1   0   2   3   1   5   0   1   0]
 [  1   4   0   4   0   2   0   1   0]
 [  5   0  16   1   2   6   2   0   1]
 [  2   0   2  55   5   6   3   2   3]
 [  0   0   2   2  11   4   1   0   2]
 [  0   3   6   9   2 122   

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create a Random Forest Classifier
modelRF = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training data
modelRF.fit(X_train, Y_train)

# Predict on the training data
X_train_prediction = modelRF.predict(X_train)

# Calculate accuracy on training data
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training Data: ', train_data_accuracy)

# Calculate precision on training data
train_data_precision = precision_score(X_train_prediction, Y_train, average='weighted')
print('Precision on Training Data: ', train_data_precision)

# Calculate recall on training data
train_data_recall = recall_score(X_train_prediction, Y_train, average='weighted')
print('Recall on Training Data: ', train_data_recall)

# Calculate F1 score on training data
train_data_f1_score = f1_score(X_train_prediction, Y_train, average='weighted')
print('F1 Score on Training Data: ', train_data_f1_score)

# Generate a confusion matrix for training data
confusion_matrix_train = confusion_matrix(Y_train, X_train_prediction)
print('Confusion Matrix (Training Data):\n', confusion_matrix_train)

# Predict on the test data
X_test_prediction = modelRF.predict(X_test)

# Calculate accuracy on test data
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test Data: ', test_data_accuracy)

# Calculate precision on test data
test_data_precision = precision_score(X_test_prediction, Y_test, average='weighted')
print('Precision on Test Data: ', test_data_precision)

# Calculate recall on test data
test_data_recall = recall_score(X_test_prediction, Y_test, average='weighted')
print('Recall on Test Data: ', test_data_recall)

# Calculate F1 score on test data
test_data_f1_score = f1_score(X_test_prediction, Y_test, average='weighted')
print('F1 Score on Test Data: ', test_data_f1_score)

# Generate a confusion matrix for test data
confusion_matrix_test = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix (Test Data):\n', confusion_matrix_test)


Accuracy on Training Data:  1.0
Precision on Training Data:  1.0
Recall on Training Data:  1.0
F1 Score on Training Data:  1.0
Confusion Matrix (Training Data):
 [[ 34   0   0   0   0   0   0   0   0]
 [  0  58   0   0   0   0   0   0   0]
 [  0   0 122   0   0   0   0   0   0]
 [  0   0   0 322   0   0   0   0   0]
 [  0   0   0   0 101   0   0   0   0]
 [  0   0   0   0   0 616   0   0   0]
 [  0   0   0   0   0   0 152   0   0]
 [  0   0   0   0   0   0   0 163   0]
 [  0   0   0   0   0   0   0   0  87]]

Accuracy on Test Data:  0.7946859903381642
Precision on Test Data:  0.8658221069548301
Recall on Test Data:  0.7946859903381642
F1 Score on Test Data:  0.8160479717565562
Confusion Matrix (Test Data):
 [[  1   0   0   4   0   8   0   0   0]
 [  0   2   1   2   0   6   0   0   1]
 [  0   0  26   2   0   5   0   0   0]
 [  1   0   2  67   2   6   0   0   0]
 [  0   0   0   2  16   4   0   0   0]
 [  0   0   0   1   0 152   1   0   0]
 [  0   0   1   3   3   5  26   0   0]
 [  0   0 

In [18]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create an SVM classifier with a linear kernel
modelSVM = SVC(kernel='linear')

# Train the model on the training data
modelSVM.fit(X_train, Y_train)

# Predict on the training data
X_train_prediction = modelSVM.predict(X_train)

# Calculate accuracy on training data
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training Data: ', train_data_accuracy)

# Calculate precision on training data
train_data_precision = precision_score(X_train_prediction, Y_train, average='weighted')
print('Precision on Training Data: ', train_data_precision)

# Calculate recall on training data
train_data_recall = recall_score(X_train_prediction, Y_train, average='weighted')
print('Recall on Training Data: ', train_data_recall)

# Calculate F1 score on training data
train_data_f1_score = f1_score(X_train_prediction, Y_train, average='weighted')
print('F1 Score on Training Data: ', train_data_f1_score)

# Generate a confusion matrix for training data
confusion_matrix_train = confusion_matrix(Y_train, X_train_prediction)
print('Confusion Matrix (Training Data):\n', confusion_matrix_train)

# Predict on the test data
X_test_prediction = modelSVM.predict(X_test)

# Calculate accuracy on test data
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test Data: ', test_data_accuracy)

# Calculate precision on test data
test_data_precision = precision_score(X_test_prediction, Y_test, average='weighted')
print('Precision on Test Data: ', test_data_precision)

# Calculate recall on test data
test_data_recall = recall_score(X_test_prediction, Y_test, average='weighted')
print('Recall on Test Data: ', test_data_recall)

# Calculate F1 score on test data
test_data_f1_score = f1_score(X_test_prediction, Y_test, average='weighted')
print('F1 Score on Test Data: ', test_data_f1_score)

# Generate a confusion matrix for test data
confusion_matrix_test = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix (Test Data):\n', confusion_matrix_test)


Accuracy on Training Data:  0.6996978851963747
Precision on Training Data:  0.7648740272638946
Recall on Training Data:  0.6996978851963747
F1 Score on Training Data:  0.7205657946973462
Confusion Matrix (Training Data):
 [[  5   0   5  13   0   6   0   5   0]
 [  0  19   0   0   1  32   4   0   2]
 [  1   2  70  10  13  20   2   3   1]
 [  0   2   8 263   3  32   7   4   3]
 [  2   0   6  10  69   9   1   3   1]
 [  2   2   7  18   9 563  14   1   0]
 [  2   1   2  33   4  26  75   8   1]
 [  1   4   3  26   0  55   4  69   1]
 [  0   2  14  21   3  11   4   7  25]]

Accuracy on Test Data:  0.6908212560386473
Precision on Test Data:  0.7530605147882037
Recall on Test Data:  0.6908212560386473
F1 Score on Test Data:  0.7110137477080251
Confusion Matrix (Test Data):
 [[  1   1   0   7   0   3   0   1   0]
 [  0   3   2   2   0   3   1   0   1]
 [  0   1  22   1   3   4   0   2   0]
 [  2   0   6  63   1   3   1   2   0]
 [  0   1   1   4  14   1   1   0   0]
 [  0   0   4   2   3 140   