In [16]:
import numpy as np
import pandas as pd                               
import os
import csv
import cv2
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics 
from sklearn.metrics import accuracy_score

In [17]:
folder1 = "D:/mine/train/Bull"

# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder1):
    # Path to the image
    path = os.path.join(folder1, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Bull.csv", index=False)



Descriptor shape 0 : (286, 128)
Descriptor shape 1 : (717, 128)
Descriptor shape 2 : (786, 128)
Descriptor shape 3 : (912, 128)
Descriptor shape 4 : (726, 128)
Descriptor shape 5 : (632, 128)
Descriptor shape 6 : (828, 128)
Descriptor shape 7 : (762, 128)
Descriptor shape 8 : (569, 128)
Descriptor shape 9 : (1000, 128)
Descriptor shape 10 : (164, 128)
Descriptor shape 11 : (193, 128)
Descriptor shape 12 : (536, 128)
Descriptor shape 13 : (838, 128)
Descriptor shape 14 : (922, 128)
Descriptor shape 15 : (538, 128)
Descriptor shape 16 : (999, 128)
Descriptor shape 17 : (85, 128)
Descriptor shape 18 : (683, 128)
Descriptor shape 19 : (209, 128)
Descriptor shape 20 : (1780, 128)
Descriptor shape 21 : (1650, 128)
Descriptor shape 22 : (660, 128)
Descriptor shape 23 : (965, 128)
Descriptor shape 24 : (468, 128)
Descriptor shape 25 : (599, 128)
Descriptor shape 26 : (124, 128)
Descriptor shape 27 : (1212, 128)
Descriptor shape 28 : (489, 128)
Descriptor shape 29 : (841, 128)
Descriptor shape 

In [18]:
folder2=r"D:/mine/train/Cattle"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder2):
    # Path to the image
    path = os.path.join(folder2, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Cattle.csv", index=False)



Descriptor shape 0 : (775, 128)
Descriptor shape 1 : (1026, 128)
Descriptor shape 2 : (786, 128)
Descriptor shape 3 : (349, 128)
Descriptor shape 4 : (403, 128)
Descriptor shape 5 : (144, 128)
Descriptor shape 6 : (1059, 128)
Descriptor shape 7 : (536, 128)
Descriptor shape 8 : (284, 128)
Descriptor shape 9 : (813, 128)
Descriptor shape 10 : (560, 128)
Descriptor shape 11 : (523, 128)
Descriptor shape 12 : (634, 128)
Descriptor shape 13 : (390, 128)
Descriptor shape 14 : (737, 128)
Descriptor shape 15 : (1094, 128)
Descriptor shape 16 : (513, 128)
Descriptor shape 17 : (766, 128)
Descriptor shape 18 : (626, 128)
Descriptor shape 19 : (844, 128)
Descriptor shape 20 : (325, 128)
Descriptor shape 21 : (801, 128)
Descriptor shape 22 : (1749, 128)
Descriptor shape 23 : (676, 128)
Descriptor shape 24 : (1718, 128)
Descriptor shape 25 : (336, 128)
Descriptor shape 26 : (909, 128)
Descriptor shape 27 : (431, 128)
Descriptor shape 28 : (827, 128)
Descriptor shape 29 : (961, 128)
Descriptor shap

In [19]:
folder3=r"D:/mine/train/Elephant"
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder3):
    # Path to the image
    path = os.path.join(folder3, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Elephant.csv", index=False)



Descriptor shape 0 : (784, 128)
Descriptor shape 1 : (1023, 128)
Descriptor shape 2 : (961, 128)
Descriptor shape 3 : (962, 128)
Descriptor shape 4 : (339, 128)
Descriptor shape 5 : (743, 128)
Descriptor shape 6 : (1094, 128)
Descriptor shape 7 : (804, 128)
Descriptor shape 8 : (492, 128)
Descriptor shape 9 : (1696, 128)
Descriptor shape 10 : (976, 128)
Descriptor shape 11 : (660, 128)
Descriptor shape 12 : (1499, 128)
Descriptor shape 13 : (1103, 128)
Descriptor shape 14 : (873, 128)
Descriptor shape 15 : (591, 128)
Descriptor shape 16 : (843, 128)
Descriptor shape 17 : (419, 128)
Descriptor shape 18 : (686, 128)
Descriptor shape 19 : (741, 128)
Descriptor shape 20 : (237, 128)
Descriptor shape 21 : (334, 128)
Descriptor shape 22 : (900, 128)
Descriptor shape 23 : (197, 128)
Descriptor shape 24 : (1312, 128)
Descriptor shape 25 : (792, 128)
Descriptor shape 26 : (350, 128)
Descriptor shape 27 : (809, 128)
Descriptor shape 28 : (478, 128)
Descriptor shape 29 : (866, 128)
Descriptor sha

In [20]:
folder4=r"D:/mine/train/Horse"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder4):
    # Path to the image
    path = os.path.join(folder4, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Horse.csv", index=False)



Descriptor shape 0 : (538, 128)
Descriptor shape 1 : (184, 128)
Descriptor shape 2 : (822, 128)
Descriptor shape 3 : (598, 128)
Descriptor shape 4 : (598, 128)
Descriptor shape 5 : (712, 128)
Descriptor shape 6 : (958, 128)
Descriptor shape 7 : (341, 128)
Descriptor shape 8 : (1269, 128)
Descriptor shape 9 : (679, 128)
Descriptor shape 10 : (582, 128)
Descriptor shape 11 : (550, 128)
Descriptor shape 12 : (267, 128)
Descriptor shape 13 : (459, 128)
Descriptor shape 14 : (513, 128)
Descriptor shape 15 : (205, 128)
Descriptor shape 16 : (1055, 128)
Descriptor shape 17 : (761, 128)
Descriptor shape 18 : (207, 128)
Descriptor shape 19 : (351, 128)
Descriptor shape 20 : (1350, 128)
Descriptor shape 21 : (572, 128)
Descriptor shape 22 : (608, 128)
Descriptor shape 23 : (723, 128)
Descriptor shape 24 : (501, 128)
Descriptor shape 25 : (328, 128)
Descriptor shape 26 : (448, 128)
Descriptor shape 27 : (439, 128)
Descriptor shape 28 : (1261, 128)
Descriptor shape 29 : (424, 128)
Descriptor shape

Descriptor shape 247 : (1665, 128)
Descriptor shape 248 : (1275, 128)
Descriptor shape 249 : (782, 128)
Descriptor shape 250 : (1311, 128)
Descriptor shape 251 : (596, 128)
Descriptor shape 252 : (675, 128)
Descriptor shape 253 : (810, 128)
Descriptor shape 254 : (260, 128)
Descriptor shape 255 : (817, 128)
Descriptor shape 256 : (607, 128)
Descriptor shape 257 : (607, 128)
Descriptor shape 258 : (1092, 128)
Descriptor shape 259 : (303, 128)
Descriptor shape 260 : (124, 128)
Descriptor shape 261 : (982, 128)
Descriptor shape 262 : (1184, 128)
Descriptor shape 263 : (579, 128)
Descriptor shape 264 : (446, 128)
Descriptor shape 265 : (405, 128)
Descriptor shape 266 : (765, 128)
Descriptor shape 267 : (852, 128)
Descriptor shape 268 : (24, 128)
Descriptor shape 269 : (832, 128)
Descriptor shape 270 : (294, 128)
Descriptor shape 271 : (163, 128)
Descriptor shape 272 : (1212, 128)
Descriptor shape 273 : (209, 128)
Descriptor shape 274 : (304, 128)
Descriptor shape 275 : (488, 128)
Descripto

In [21]:
folder5=r"D:/mine/train/Leopard"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder5):
    # Path to the image
    path = os.path.join(folder5, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Leopard.csv", index=False)



Descriptor shape 0 : (1132, 128)
Descriptor shape 1 : (1721, 128)
Descriptor shape 2 : (838, 128)
Descriptor shape 3 : (309, 128)
Descriptor shape 4 : (1317, 128)
Descriptor shape 5 : (662, 128)
Descriptor shape 6 : (752, 128)
Descriptor shape 7 : (1917, 128)
Descriptor shape 8 : (1029, 128)
Descriptor shape 9 : (1399, 128)
Descriptor shape 10 : (1488, 128)
Descriptor shape 11 : (1075, 128)
Descriptor shape 12 : (737, 128)
Descriptor shape 13 : (859, 128)
Descriptor shape 14 : (1018, 128)
Descriptor shape 15 : (1466, 128)
Descriptor shape 16 : (848, 128)
Descriptor shape 17 : (628, 128)
Descriptor shape 18 : (936, 128)
Descriptor shape 19 : (760, 128)
Descriptor shape 20 : (1056, 128)
Descriptor shape 21 : (56, 128)
Descriptor shape 22 : (1054, 128)
Descriptor shape 23 : (1556, 128)
Descriptor shape 24 : (1267, 128)
Descriptor shape 25 : (1009, 128)
Descriptor shape 26 : (896, 128)
Descriptor shape 27 : (768, 128)
Descriptor shape 28 : (1044, 128)
Descriptor shape 29 : (1162, 128)
Desc

In [22]:
folder6=r"D:/mine/train/Monkey"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder6):
    # Path to the image
    path = os.path.join(folder6, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Monkey.csv", index=False)



Descriptor shape 0 : (45, 128)
Descriptor shape 1 : (1353, 128)
Descriptor shape 2 : (310, 128)
Descriptor shape 3 : (673, 128)
Descriptor shape 4 : (208, 128)
Descriptor shape 5 : (549, 128)
Descriptor shape 6 : (1250, 128)
Descriptor shape 7 : (420, 128)
Descriptor shape 8 : (834, 128)
Descriptor shape 9 : (1304, 128)
Descriptor shape 10 : (497, 128)
Descriptor shape 11 : (856, 128)
Descriptor shape 12 : (433, 128)
Descriptor shape 13 : (238, 128)
Descriptor shape 14 : (337, 128)
Descriptor shape 15 : (277, 128)
Descriptor shape 16 : (704, 128)
Descriptor shape 17 : (809, 128)
Descriptor shape 18 : (146, 128)
Descriptor shape 19 : (1021, 128)
Descriptor shape 20 : (914, 128)
Descriptor shape 21 : (601, 128)
Descriptor shape 22 : (172, 128)
Descriptor shape 23 : (522, 128)
Descriptor shape 24 : (1644, 128)
Descriptor shape 25 : (507, 128)
Descriptor shape 26 : (546, 128)
Descriptor shape 27 : (693, 128)
Descriptor shape 28 : (604, 128)
Descriptor shape 29 : (330, 128)
Descriptor shape

Descriptor shape 246 : (1172, 128)
Descriptor shape 247 : (893, 128)
Descriptor shape 248 : (1151, 128)
Descriptor shape 249 : (1157, 128)
Descriptor shape 250 : (146, 128)
Descriptor shape 251 : (215, 128)
Descriptor shape 252 : (631, 128)
Descriptor shape 253 : (660, 128)
Descriptor shape 254 : (131, 128)
Descriptor shape 255 : (518, 128)
Descriptor shape 256 : (885, 128)
Descriptor shape 257 : (90, 128)
Descriptor shape 258 : (907, 128)
Descriptor shape 259 : (420, 128)
Descriptor shape 260 : (675, 128)
Descriptor shape 261 : (619, 128)
Descriptor shape 262 : (1219, 128)
Descriptor shape 263 : (1166, 128)
Descriptor shape 264 : (343, 128)
Descriptor shape 265 : (1400, 128)
Descriptor shape 266 : (288, 128)
Descriptor shape 267 : (299, 128)
Descriptor shape 268 : (540, 128)
Descriptor shape 269 : (263, 128)
Descriptor shape 270 : (820, 128)
Descriptor shape 271 : (548, 128)
Descriptor shape 272 : (260, 128)
Descriptor shape 273 : (178, 128)
Descriptor shape 274 : (877, 128)
Descripto

Descriptor shape 490 : (808, 128)
Descriptor shape 491 : (251, 128)
Descriptor shape 492 : (378, 128)
Descriptor shape 493 : (924, 128)
Descriptor shape 494 : (375, 128)
Descriptor shape 495 : (640, 128)
Descriptor shape 496 : (498, 128)
Descriptor shape 497 : (625, 128)
Descriptor shape 498 : (506, 128)
Descriptor shape 499 : (624, 128)
Descriptor shape 500 : (744, 128)
Descriptor shape 501 : (1737, 128)
Descriptor shape 502 : (662, 128)
Descriptor shape 503 : (594, 128)
Descriptor shape 504 : (559, 128)
Descriptor shape 505 : (312, 128)
Descriptor shape 506 : (483, 128)
Descriptor shape 507 : (218, 128)
Descriptor shape 508 : (1062, 128)
Descriptor shape 509 : (446, 128)
Descriptor shape 510 : (1627, 128)
Descriptor shape 511 : (589, 128)
Descriptor shape 512 : (1165, 128)
Descriptor shape 513 : (1611, 128)
Descriptor shape 514 : (656, 128)
Descriptor shape 515 : (176, 128)
Descriptor shape 516 : (1234, 128)
Descriptor shape 517 : (1702, 128)
Descriptor shape 518 : (1493, 128)
Descri

Descriptor shape 735 : (218, 128)
Descriptor shape 736 : (272, 128)
Descriptor shape 737 : (976, 128)
Descriptor shape 738 : (906, 128)
Descriptor shape 739 : (186, 128)
Descriptor shape 740 : (2395, 128)
Descriptor shape 741 : (225, 128)
Descriptor shape 742 : (905, 128)
Descriptor shape 743 : (204, 128)
Descriptor shape 744 : (252, 128)
Descriptor shape 745 : (706, 128)
Descriptor shape 746 : (1088, 128)
Descriptor shape 747 : (805, 128)
Descriptor shape 748 : (1278, 128)
Descriptor shape 749 : (268, 128)
Descriptor shape 750 : (431, 128)
Descriptor shape 751 : (912, 128)
Descriptor shape 752 : (321, 128)
Descriptor shape 753 : (515, 128)
Descriptor shape 754 : (300, 128)
Descriptor shape 755 : (575, 128)
Descriptor shape 756 : (1906, 128)
Descriptor shape 757 : (394, 128)
Descriptor shape 758 : (769, 128)
Descriptor shape 759 : (354, 128)
Descriptor shape 760 : (573, 128)
Descriptor shape 761 : (1037, 128)
Descriptor shape 762 : (1319, 128)
Descriptor shape 763 : (303, 128)
Descript

In [23]:
folder7=r"D:/mine/train/Pig"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder7):
    # Path to the image
    path = os.path.join(folder7, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Pig.csv", index=False)



Descriptor shape 0 : (417, 128)
Descriptor shape 1 : (1269, 128)
Descriptor shape 2 : (1592, 128)
Descriptor shape 3 : (509, 128)
Descriptor shape 4 : (1600, 128)
Descriptor shape 5 : (838, 128)
Descriptor shape 6 : (287, 128)
Descriptor shape 7 : (888, 128)
Descriptor shape 8 : (1289, 128)
Descriptor shape 9 : (2320, 128)
Descriptor shape 10 : (156, 128)
Descriptor shape 11 : (973, 128)
Descriptor shape 12 : (770, 128)
Descriptor shape 13 : (609, 128)
Descriptor shape 14 : (358, 128)
Descriptor shape 15 : (1123, 128)
Descriptor shape 16 : (349, 128)
Descriptor shape 17 : (445, 128)
Descriptor shape 18 : (1788, 128)
Descriptor shape 19 : (1153, 128)
Descriptor shape 20 : (841, 128)
Descriptor shape 21 : (835, 128)
Descriptor shape 22 : (675, 128)
Descriptor shape 23 : (1546, 128)
Descriptor shape 24 : (1316, 128)
Descriptor shape 25 : (1364, 128)
Descriptor shape 26 : (856, 128)
Descriptor shape 27 : (1867, 128)
Descriptor shape 28 : (516, 128)
Descriptor shape 29 : (737, 128)
Descript

In [24]:
folder8=r"D:/mine/train/Rabbit"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder8):
    # Path to the image
    path = os.path.join(folder8, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Rabbit.csv", index=False)



Descriptor shape 0 : (411, 128)
Descriptor shape 1 : (180, 128)
Descriptor shape 2 : (214, 128)
Descriptor shape 3 : (1130, 128)
Descriptor shape 4 : (1232, 128)
Descriptor shape 5 : (1959, 128)
Descriptor shape 6 : (1234, 128)
Descriptor shape 7 : (550, 128)
Descriptor shape 8 : (1485, 128)
Descriptor shape 9 : (1316, 128)
Descriptor shape 10 : (1251, 128)
Descriptor shape 11 : (654, 128)
Descriptor shape 12 : (281, 128)
Descriptor shape 13 : (736, 128)
Descriptor shape 14 : (1124, 128)
Descriptor shape 15 : (1479, 128)
Descriptor shape 16 : (172, 128)
Descriptor shape 17 : (440, 128)
Descriptor shape 18 : (177, 128)
Descriptor shape 19 : (759, 128)
Descriptor shape 20 : (799, 128)
Descriptor shape 21 : (450, 128)
Descriptor shape 22 : (1079, 128)
Descriptor shape 23 : (1378, 128)
Descriptor shape 24 : (618, 128)
Descriptor shape 25 : (566, 128)
Descriptor shape 26 : (1195, 128)
Descriptor shape 27 : (1032, 128)
Descriptor shape 28 : (1073, 128)
Descriptor shape 29 : (390, 128)
Descri

In [25]:
folder9=r"D:/mine/train/Sheep"
# Initialize a counter for printing descriptor shape
i = 0

# Create an empty list to store image descriptors
data = []

# Resize dimensions
resize = (280, 430)

# Initialize SIFT detector
sift = cv2.SIFT_create()

for filename in os.listdir(folder9):
    # Path to the image
    path = os.path.join(folder9, filename)
    
    # Read the image
    img = cv2.imread(path)
    
    # Check if the image is loaded successfully
    if img is not None:
        # Resize the image
        img = cv2.resize(img, resize)
        
        # Convert the image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Detect SIFT keypoints and descriptors
        keypoints, descriptors = sift.detectAndCompute(gray, None)
        
        # Convert the descriptor array into a DataFrame format
        out = pd.DataFrame(descriptors)
        
        # Append the descriptor data to the list
        data.append(out)
        
        # Print the descriptor shape
        print("Descriptor shape", i, ":", out.shape)
        
        i += 1

# Combine all the descriptor data into a single DataFrame
descriptor_data = pd.concat(data, ignore_index=True)

# Save the descriptor data to a CSV file
descriptor_data.to_csv("D:/cv_final_project/z/Sheep.csv", index=False)



Descriptor shape 0 : (1008, 128)
Descriptor shape 1 : (1293, 128)
Descriptor shape 2 : (681, 128)
Descriptor shape 3 : (1170, 128)
Descriptor shape 4 : (321, 128)
Descriptor shape 5 : (639, 128)
Descriptor shape 6 : (351, 128)
Descriptor shape 7 : (238, 128)
Descriptor shape 8 : (702, 128)
Descriptor shape 9 : (313, 128)
Descriptor shape 10 : (661, 128)
Descriptor shape 11 : (284, 128)
Descriptor shape 12 : (1166, 128)
Descriptor shape 13 : (1505, 128)
Descriptor shape 14 : (448, 128)
Descriptor shape 15 : (1075, 128)
Descriptor shape 16 : (689, 128)
Descriptor shape 17 : (254, 128)
Descriptor shape 18 : (780, 128)
Descriptor shape 19 : (327, 128)
Descriptor shape 20 : (984, 128)
Descriptor shape 21 : (1636, 128)
Descriptor shape 22 : (1378, 128)
Descriptor shape 23 : (681, 128)
Descriptor shape 24 : (706, 128)
Descriptor shape 25 : (992, 128)
Descriptor shape 26 : (521, 128)
Descriptor shape 27 : (319, 128)
Descriptor shape 28 : (1643, 128)
Descriptor shape 29 : (191, 128)
Descriptor 

In [26]:
data1 = pd.read_csv(r'D:/cv_final_project/z/Bull.csv',header=None,dtype='uint8')
data1=data1.astype(np.uint8) 
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1       93   12    0    4   14    7    8   73  137   29  ...    3    3    0   
2        1    0    3   18    6    8    2    3   10    1  ...    0    0   13   
3        1    1   28   67    8   13   42   10    4   14  ...    0    1   12   
4       10    1    0   12  140    2    0    2   78    1  ...  110   43   47   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
34273    5   12   17   10    6   17   45   19   60   20  ...    0   76    2   
34274   44    1    0    0    0    4    3   16  174    3  ...    0    0   20   
34275    0    0    0   22   38    0    0    0    8    6  ...    2   51   47   
34276    0    0    2   11  122   74   11    4   10    0  ...    2    1    0   
34277    1    3    0    0    4    5    0    0    8   42  ...   10   96   35   

       121  122  123  124  125  126  127  
0      121  122  123  124  125  126  127  
1        1   55   85    7    4    8    1  
2       17   34   39    7    6    5    6  
3        7    0    0   15    5    0    0  
4        9    3    0    0    0   51   67  
...    ...  ...  ...  ...  ...  ...  ...  
34273    0    0   36   92    1    0    1  
34274   10    0    0    0    0    0    0  
34275   24   14   31   19    5    2    1  
34276    0    0    0    3   13    1    0  
34277    1    0   16   62   26    2    8  

[34278 rows x 128 columns]

In [27]:
data2 = pd.read_csv(r'D:/cv_final_project/z/Cattle.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8) 
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1        0    0    0    0    0    0    0    0    0    0  ...   23  116   24   
2        0    0    0    0    0    0    0    0    5    5  ...    5   74    9   
3        3   46  134   48   64   32    7    1   42  134  ...    0    0    0   
4       53    5    3   58  126   15    2   37  112    1  ...    1   26   52   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
43642   67   60    6    6    0    0    0    3   84   55  ...    0    0  102   
43643   15   32    7    8   62   33    4    2   97   23  ...   52   17    2   
43644    0    0    0    0    0    0    0    0   38   30  ...    0   81   10   
43645    0    0    0    0    0    0    0    0    3    3  ...    0    0    1   
43646  102    2    0    1    4    7    9   51  118    0  ...    0    0    0   

       121  122  123  124  125  126  127  
0      121  122  123  124  125  126  127  
1       12   27   17   14   42   86   43  
2        4    6   69   31    0    0    8  
3        0    0    0    0    0    0    0  
4        2    3    2    0    0    1   48  
...    ...  ...  ...  ...  ...  ...  ...  
43642   38    1    0   13   14    1    3  
43643    0    0   52  141    3    1    1  
43644    1    0   14  150   17   12    8  
43645    3    5   37  116    8    0    1  
43646    0    0    0    0    0    0    0  

[43647 rows x 128 columns]

In [28]:
data3 = pd.read_csv(r'D:/cv_final_project/z/Elephant.csv',header=None,dtype='uint8')
data3=data3.astype(np.uint8) 
data3

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1         1    0    9  138  138   29    6    1   48   19  ...    0    1    0   
2         0    0    0    0    0    0    0    0    4    1  ...    5    7   40   
3         8    9   19   12   14    2    1    5   69   33  ...    9   43   61   
4         4   15   11    4   11   18   47    5  113   38  ...   11    6    5   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
124925   14   23   24   11   35   49    1    0   58   16  ...    2    2    0   
124926    8    2   35  116   37   24   49   35   13    2  ...   23   15    1   
124927    0    0    0    0    0    0    0    0    2    1  ...  115  118   39   
124928    0    0    0    0    0    0    0    0   14   11  ...    0    9   69   
124929    0    0    0    4    7    0    0    0  124   14  ...    2   14   27   

        121  122  123  124  125  126  127  
0       121  122  123  124  125  126  127  
1         0    0    0    0    0    0    0  
2        38   18    3    8    5    8   13  
3        19   13    7    4   18   15   30  
4        68   51   16    4    9   12    3  
...     ...  ...  ...  ...  ...  ...  ...  
124925    0   10    8    1    1    0    0  
124926   40   65   30   23   10    2    1  
124927   14   21   27    9    6   46   83  
124928   11    6    8    0    0    0   52  
124929    9    1    8  140   63    0    3  

[124930 rows x 128 columns]

In [29]:
data4 = pd.read_csv(r'D:/cv_final_project/z/Horse.csv',header=None,dtype='uint8')
data4=data4.astype(np.uint8) data4 = pd.read_csv(r'D:/cv_final_project/z/Horse.csv',header=None,dtype='uint8')
data4=data4.astype(np.uint8) 
data4

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1        25    7    4   13   47   73   20   33  134    7  ...   11   12   25   
2         3   19    7   10    0    0    0    0   66   27  ...    0   26   30   
3        24   14    1    1    0    1    1    6  169  160  ...    1   25   39   
4         0    0    4   19    5    4   22    2    5    1  ...    0    7   68   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
260557    1    1    0    0    0    0    0    0   22    8  ...    0    3    0   
260558   96   25    4    0    0    0    0   18  156   17  ...    0    0    0   
260559    0    0    0    0    0    0    0    0   11    1  ...   22    7   78   
260560    9    5    6   39   17    0    0    0   21    3  ...   75   36   10   
260561  107    1    0    0    0    0    7   96  129    4  ...   78   85   23   

        121  122  123  124  125  126  127  
0       121  122  123  124  125  126  127  
1        25    2    0    1    1    7   13  
2        10    0    0    0    0    0    3  
3         3    0    0    0    0    6   25  
4        70    6    1   11   40   35   13  
...     ...  ...  ...  ...  ...  ...  ...  
260557    0    0   21   88   21    4    0  
260558    0    0    0    1    1    0    0  
260559   64    7   10   13    8   19   15  
260560    5    0   44  131   25    1    5  
260561   21   11   49   58    8   21   22  

[260562 rows x 128 columns]

In [30]:
data5 = pd.read_csv(r'D:/cv_final_project/z/Leopard.csv',header=None,dtype='uint8')
data5=data5.astype(np.uint8) 
data5

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1         0    0    0    0    0    0    0    0    1    3  ...   30   46    8   
2        33    0    0    0   19   73   26   31  110   21  ...    1   46   68   
3         3    0    0   52  130    9    4   19  130   10  ...    4   80   67   
4       112   31    1    0    1    2    5   98   90  128  ...    1   38   16   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
136676    3   17   33  124    5    0    0    0   77   77  ...   52  124    2   
136677    0    0    0    0    0    0    0    0    6    1  ...   20  103   55   
136678    0    1    1    0    0    0    0    0   66  118  ...   19   49    0   
136679   21   13   28  117   21    0    0    6    3    1  ...    4   30    0   
136680    5  134   96    0    0    0    0    0   16  134  ...    0   18    0   

        121  122  123  124  125  126  127  
0       121  122  123  124  125  126  127  
1        34   56   40    5    1    0    0  
2        30    0    0    0    0    0    0  
3         1    2   15    5    0    0   29  
4         0    0    0    0    0    0    6  
...     ...  ...  ...  ...  ...  ...  ...  
136676    0    0    0    0    0   10   15  
136677    2    0    3   40  107   47  119  
136678    7   21    4   36  111   21    5  
136679    0    0    0    0    0    0    0  
136680    0    0    0    0    0    0    0  

[136681 rows x 128 columns]

In [31]:
data6 = pd.read_csv(r'D:/cv_final_project/z/Monkey.csv',header=None,dtype='uint8')
data6=data6.astype(np.uint8) 
data6

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1         0    0    1   43   45    0    0    0   33   17  ...   11   59   12   
2         0    9    5    4   68   58    0    0    7    0  ...    5   67   62   
3        23    1    0    8   98    9    0    9    3    0  ...    0    0   63   
4        32   27    3    2   62  121   96   38   60    8  ...    0   40    7   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
536616  117    0    0   26   13    1    6  128   31    3  ...    5    9    2   
536617    0    0    0    0    0    0    0    0   79   45  ...    2   14  102   
536618   13    2    0    9   47    0    0    0   57    2  ...    0    0  105   
536619    0    2   13   25    9    0    0    0    0    0  ...    2   80   42   
536620    0    0    0    0    0    0    0    0    2    4  ...    1   16   57   

        121  122  123  124  125  126  127  
0       121  122  123  124  125  126  127  
1         0    0   22   68    0    0    2  
2         2    1   26   25    0    0    8  
3       125    0    0    0    3    2    2  
4        10   12   15   31    0    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
536616    0    0    0    3    2    7   20  
536617   76   20   35   27    9   33   48  
536618  112    3    0    0    0    0    1  
536619   14    4   18   10    1    2   46  
536620   48    7   10   29    6    1    2  

[536621 rows x 128 columns]

In [32]:
data7 = pd.read_csv(r'D:/cv_final_project/z/Pig.csv',header=None,dtype='uint8')
data7=data7.astype(np.uint8) 
data7

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1         3   44  143   10    0    0    0    0   72  143  ...    9   35    1   
2        13   71    4    1    3   11    3    1  127   33  ...   62   33    1   
3         0   29   72    2    0    0    0    0    0   74  ...   11  141   70   
4        49   71    2    1    4    3    0    0   42   26  ...   85  143   31   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
186384    0    0    9   20   42    8    1    0   56    7  ...   12   43   37   
186385    0    0   17   39   20   28    1    0  101   10  ...    0   45  116   
186386    0    7    6    1    0    0    0    0   17   36  ...   14   70   76   
186387    4  161   28    1    1    1    0    1    4  112  ...    0   58  161   
186388    2    0    0    0    0   18   31    7  145   11  ...   20   86   32   

        121  122  123  124  125  126  127  
0       121  122  123  124  125  126  127  
1         1    0    1    2    3    0    0  
2         0    0    1    0    0    6   13  
3        17    0    0    0    0    2   19  
4         0    0    0    0    0   13   68  
...     ...  ...  ...  ...  ...  ...  ...  
186384  122    2    0    1    2    4    5  
186385   21    0    0    0    0    0    9  
186386   43    5    7    2    0    0   13  
186387   24    0    0    0    0    0   18  
186388   59   25    8   19   43   10   18  

[186389 rows x 128 columns]

In [33]:
data8 = pd.read_csv(r'D:/cv_final_project/z/Rabbit.csv',header=None,dtype='uint8')
data8=data8.astype(np.uint8) 
data8

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1        10    9    0    0    0    0    0    0   98   62  ...    1    4    2   
2         4    1    0    0    0    0    0    1   78    2  ...    1   34    4   
3         0    0    0    0    0    0    0    0    5    4  ...    5   38    1   
4         6    3    1    0    0    0    1    4   85    4  ...    0   80   24   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
141755    1    2    5    7   18   24    2    0    4    2  ...    4    2  126   
141756  121  104   14    3    1    0    1    5   34   60  ...    1    0    0   
141757    4    8    1    0    0    0    1    1   41   84  ...   17   50   43   
141758    0    1    7   10    0    0    0    0   11   11  ...    0    2    0   
141759   26   81   13   10   34   19    2    1    5    7  ...   91  127    0   

        121  122  123  124  125  126  127  
0       121  122  123  124  125  126  127  
1         0    0    0    6   22    5    0  
2         1    0    2    5    2    0    1  
3         2    2    0    8   75   28    1  
4         0    0    0    3    1    0    9  
...     ...  ...  ...  ...  ...  ...  ...  
141755  126   17    2    3   11    4    4  
141756    0    0    0    0    0    0    0  
141757   61   38   74  103    3    1    9  
141758   23   32  114   93    1    0    0  
141759    0    0    0    0    1    4    1  

[141760 rows x 128 columns]

In [34]:
data9 = pd.read_csv(r'D:/cv_final_project/z/Sheep.csv',header=None,dtype='uint8')
data9=data9.astype(np.uint8) 
data9

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1       17    5   26   23   11   96  117   63    3    7  ...   59   91    0   
2        0    1    0    0    0    0    0    0    9   48  ...   29  144   32   
3        0    0   22   18    0    0    0    0    0   22  ...    0   18    3   
4        8   75   87   12   16    6    6    8   24  142  ...    0    0   19   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
81533    0    8   18   42   97   14    0    0   34   42  ...   14  121    2   
81534    0    1  129   36    1    3    5    3    4   58  ...   13   90   89   
81535    0    0    0    0    1    1   16   25   46   34  ...   73  109    2   
81536   11   74   49    1    0    3    2    2   46  117  ...    4    0    7   
81537    0    0    0    1    1    4   39    6   23    0  ...   39    5   68   

       121  122  123  124  125  126  127  
0      121  122  123  124  125  126  127  
1        3    4   27   65   14    6    1  
2        3    0    2   26   16   25  145  
3       24   81   93    5    0    0    1  
4       48   28    8   21    5    2    5  
...    ...  ...  ...  ...  ...  ...  ...  
81533    2    7   41   67    8    2    1  
81534    6    0    0    1   48   44   22  
81535    1    2    9   44  127   71    8  
81536   86   33    3    5    2    0    1  
81537  129   22   17   17   10   27   11  

[81538 rows x 128 columns]

In [35]:
import pandas as pd
data = pd.concat([data1, data2, data3, data4,data5,data6,data7,data8,data9], ignore_index=True)
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0          0    1    2    3    4    5    6    7    8    9  ...  118  119  120   
1         93   12    0    4   14    7    8   73  137   29  ...    3    3    0   
2          1    0    3   18    6    8    2    3   10    1  ...    0    0   13   
3          1    1   28   67    8   13   42   10    4   14  ...    0    1   12   
4         10    1    0   12  140    2    0    2   78    1  ...  110   43   47   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1546401    0    8   18   42   97   14    0    0   34   42  ...   14  121    2   
1546402    0    1  129   36    1    3    5    3    4   58  ...   13   90   89   
1546403    0    0    0    0    1    1   16   25   46   34  ...   73  109    2   
1546404   11   74   49    1    0    3    2    2   46  117  ...    4    0    7   
1546405    0    0    0    1    1    4   39    6   23    0  ...   39    5   68   

         121  122  123  124  125  126  127  
0        121  122  123  124  125  126  127  
1          1   55   85    7    4    8    1  
2         17   34   39    7    6    5    6  
3          7    0    0   15    5    0    0  
4          9    3    0    0    0   51   67  
...      ...  ...  ...  ...  ...  ...  ...  
1546401    2    7   41   67    8    2    1  
1546402    6    0    0    1   48   44   22  
1546403    1    2    9   44  127   71    8  
1546404   86   33    3    5    2    0    1  
1546405  129   22   17   17   10   27   11  

[1546406 rows x 128 columns]

In [36]:
#For data1
kmeans_data1 = KMeans(n_clusters=5, n_init=10)
kmeans_data1.fit(data1)

#For data2
kmeans_data2 = KMeans(n_clusters=5, n_init=10)
kmeans_data2.fit(data2)

#For data3
kmeans_data3 = KMeans(n_clusters=5, n_init=10)
kmeans_data3.fit(data3)

#For data4
kmeans_data4 = KMeans(n_clusters=5, n_init=10)
kmeans_data4.fit(data4)

#For data5
kmeans_data5 = KMeans(n_clusters=5, n_init=10)
kmeans_data5.fit(data5)

#For data6
kmeans_data6 = KMeans(n_clusters=5, n_init=10)
kmeans_data6.fit(data6)

#For data7
kmeans_data7 = KMeans(n_clusters=5, n_init=10)
kmeans_data7.fit(data7)

#For data8
kmeans_data8 = KMeans(n_clusters=5, n_init=10)
kmeans_data8.fit(data8)

#For data8
kmeans_data9 = KMeans(n_clusters=5, n_init=10)
kmeans_data9.fit(data9)

KMeans(n_clusters=5, n_init=10)

In [37]:
import pickle
# Save the model to disk for data 1
filename_data1 = 'Kmeans_CL_5_Model_data1.sav'
with open(filename_data1, 'wb') as file:
    pickle.dump(kmeans_data1, file)
    
# Save the model to disk for data2
filename_data2 = 'Kmeans_CL_5_Model_data2.sav'
with open(filename_data2, 'wb') as file:
    pickle.dump(kmeans_data2, file)
    
# Save the model to disk for data2
filename_data3 = 'Kmeans_CL_5_Model_data3.sav'
with open(filename_data3, 'wb') as file:
    pickle.dump(kmeans_data3, file)
    
# Save the model to disk for data2
filename_data4 = 'Kmeans_CL_5_Model_data4.sav'
with open(filename_data4, 'wb') as file:
    pickle.dump(kmeans_data4, file)
    
filename_data5 = 'Kmeans_CL_5_Model_data5.sav'
with open(filename_data5, 'wb') as file:
    pickle.dump(kmeans_data5, file)

filename_data6 = 'Kmeans_CL_5_Model_data6.sav'
with open(filename_data6, 'wb') as file:
    pickle.dump(kmeans_data6, file)
    
filename_data7 = 'Kmeans_CL_5_Model_data7.sav'
with open(filename_data7, 'wb') as file:
    pickle.dump(kmeans_data7, file)
    
filename_data8 = 'Kmeans_CL_5_Model_data8.sav'
with open(filename_data8, 'wb') as file:
    pickle.dump(kmeans_data8, file)

filename_data9 = 'Kmeans_CL_5_Model_data9.sav'
with open(filename_data9, 'wb') as file:
    pickle.dump(kmeans_data9, file)

print('complete')

complete


In [38]:

# Compute histogram of trained Kmeans of data1
hist_data1 = np.histogram(kmeans_data1.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data1:')
print(hist_data1, "\n")

# Compute histogram of trained Kmeans of data1
hist_data2 = np.histogram(kmeans_data2.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data2:')
print(hist_data2, "\n")

# Compute histogram of trained Kmeans of data1
hist_data3 = np.histogram(kmeans_data3.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data3:')
print(hist_data3, "\n")

# Compute histogram of trained Kmeans of data1
hist_data4 = np.histogram(kmeans_data4.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data4:')
print(hist_data4, "\n")

# Compute histogram of trained Kmeans of data1
hist_data5 = np.histogram(kmeans_data5.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data5:')
print(hist_data5, "\n")

# Compute histogram of trained Kmeans of data1
hist_data6 = np.histogram(kmeans_data6.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data6:')
print(hist_data6, "\n")

# Compute histogram of trained Kmeans of data1
hist_data7 = np.histogram(kmeans_data7.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data7:')
print(hist_data7, "\n")

# Compute histogram of trained Kmeans of data1
hist_data8 = np.histogram(kmeans_data8.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data8:')
print(hist_data8, "\n")

# Compute histogram of trained Kmeans of data1
hist_data9 = np.histogram(kmeans_data9.labels_, bins=[0, 1, 2, 3, 4, 5])
print('Histogram of trained kmeans for data9:')
print(hist_data9, "\n")

Histogram of trained kmeans for data1:
(array([ 6039, 10428,  5378,  7961,  4472], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data2:
(array([12516,  6721, 10044,  5477,  8889], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data3:
(array([20774, 22629, 27972, 31273, 22282], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data4:
(array([64724, 38870, 60754, 54783, 41431], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data5:
(array([33571, 28580, 25721, 25802, 23007], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data6:
(array([122675,  90552,  93125, 121148, 109121], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data7:
(array([32512, 45165, 44016, 31881, 32815], dtype=int64), array([0, 1, 2, 3, 4, 5])) 

Histogram of trained kmeans for data8:
(array([32841, 26389, 24556, 24174, 33800], dtype=int64), array([0, 1, 2, 

In [39]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path 
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data1.predict(array_double)
    
    hist_data1=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data1[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output1 = pd.DataFrame(data)
#add row class 
Output1["Class"] = 1 
csv_data=Output1.to_csv(r'D:/cv_final_project\z\Dataset1.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [40]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder2):
    #path 
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data2.predict(array_double)
    
    hist_data2=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data2[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output2 = pd.DataFrame(data)
#add row class 
Output2["Class"] = 2
csv_data=Output2.to_csv(r'D:/cv_final_project\z\Dataset2.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [41]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder3):
    #path 
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data3.predict(array_double)
    
    hist_data3=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data3[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output3 = pd.DataFrame(data)
#add row class 
Output3["Class"] = 3
csv_data=Output3.to_csv(r'D:/cv_final_project\z\Dataset3.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [42]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder4):
    #path 
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data4.predict(array_double)
    
    hist_data4=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data4[0])
    #k=k+1

Output4 = pd.DataFrame(data)
Output4["Class"] = 4
csv_data=Output4.to_csv(r'D:/cv_final_project\z\Dataset4.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [43]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder5):
    #path 
    path=os.path.join(folder5,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data5.predict(array_double)
    
    hist_data5=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data5[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output5 = pd.DataFrame(data)
#add row class 
Output5["Class"] = 5
csv_data=Output5.to_csv(r'D:/cv_final_project\z\Dataset5.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [44]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder6):
    #path 
    path=os.path.join(folder6,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data6.predict(array_double)
    
    hist_data6=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data6[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output6 = pd.DataFrame(data)
#add row class 
Output6["Class"] = 6
csv_data=Output6.to_csv(r'D:/cv_final_project\z\Dataset6.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [45]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder7):
    #path 
    path=os.path.join(folder7,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data7.predict(array_double)
    
    hist_data7=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data7[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output7 = pd.DataFrame(data)
#add row class 
Output7["Class"] = 7
csv_data=Output7.to_csv(r'D:/cv_final_project\z\Dataset7.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [46]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder8):
    #path 
    path=os.path.join(folder8,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data8.predict(array_double)
    
    hist_data8=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data8[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output8 = pd.DataFrame(data)
#add row class 
Output8["Class"] = 8
csv_data=Output8.to_csv(r'D:/cv_final_project\z\Dataset8.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [47]:
#performing kmeans prediction of the entire bottle dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder9):
    #path 
    path=os.path.join(folder9,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans_data9.predict(array_double)
    
    hist_data9=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist_data9[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output9 = pd.DataFrame(data)
#add row class 
Output9["Class"] = 9
csv_data=Output1.to_csv(r'D:/cv_final_project\z\Dataset9.csv', mode='a',header=False,index=False)

print("Complete")

Complete


In [48]:
print("Bull")
print(Output1)

Bull
      0    1    2    3    4  Class
0    50   76   65   58   37      1
1    75  237  128  157  120      1
2   148  236  138  158  106      1
3    93  275  190  194  160      1
4   179  209  103  152   83      1
5    65  287   82  136   62      1
6   166  275  120  176   91      1
7   163  212  110  160  117      1
8    68  198   81  113  109      1
9   179  312  119  346   44      1
10   78   35   16   34    1      1
11   95   56   13   26    3      1
12  169  135   65  113   54      1
13  119  199  173  161  186      1
14  259  244  141  154  124      1
15  191  126   65  114   42      1
16  116  300  166  239  178      1
17   30   33    2   19    1      1
18   95  250   92  119  127      1
19   83   52   13   48   13      1
20   97  554  307  555  267      1
21  163  470  334  438  245      1
22   41  325   85  172   37      1
23   42  405  141  323   54      1
24  111  138   83   80   56      1
25   98  120  157   71  153      1
26   34   23   24   29   14      1
27  147  308  2

In [49]:
print("Cattle")
print(Output2)

Cattle
      0    1    2    3    4  Class
0   242  110  177   77  169      2
1   395  108  312  103  108      2
2   227  137  162  115  145      2
3    82   61   57   53   96      2
4   114   30  106   13  140      2
..  ...  ...  ...  ...  ...    ...
65  450   98  221  116  101      2
66  308   73  289   49   71      2
67  101   59   88   31  111      2
68   58   27   42   24   84      2
69  248  223  183  145  195      2

[70 rows x 6 columns]


In [50]:
print("Elephant")
print(Output3)

Elephant
       0    1    2    3    4  Class
0     79  149  246  205  105      3
1    134  178  262  295  154      3
2     87   97  380  338   59      3
3     80  242  266  322   52      3
4     42  149   61   47   40      3
..   ...  ...  ...  ...  ...    ...
150  187  181  503  471  179      3
151  264   95   72   84  413      3
152   64   84   63   43   55      3
153  231  210   93  117  229      3
154  188   86   84  135  176      3

[155 rows x 6 columns]


In [51]:
print("Horse")
print(Output4)

Horse
       0    1    2    3    4  Class
0     80   81   92  216   69      4
1     49   31   54   35   15      4
2    169  161  134  172  186      4
3    158   76  164  120   80      4
4    124   95  126  179   74      4
..   ...  ...  ...  ...  ...    ...
395  114   26   34   57   44      4
396  225  138  232  212   84      4
397  379  123  279  133  161      4
398  289  190  339  188  170      4
399   54   61   36   68   55      4

[400 rows x 6 columns]


In [52]:
print("Leopard")
print(Output5)

Leopard
       0    1    2    3    4  Class
0    180  173  316  241  222      5
1    358  307  491  362  203      5
2    144  113  192  194  195      5
3     82  112   14   45   56      5
4    389  376  265  221   66      5
..   ...  ...  ...  ...  ...    ...
118  543  410  270  257  277      5
119  129  119  129   88  177      5
120   94  112   96  151  257      5
121  175  173  229  232  158      5
122  144  123  170  159  111      5

[123 rows x 6 columns]


In [53]:
print("Monkey")
print(Output6)

Monkey
       0    1    2    3    4  Class
0      4    8   13    7   13      6
1    202  253  374  275  249      6
2     33   69   23   35  150      6
3    148  105  147  116  157      6
4     19   42   10   20  117      6
..   ...  ...  ...  ...  ...    ...
765  319  104  140  290  168      6
766  112  134  183  160  129      6
767   33   47   28   43   50      6
768   25    6   19   28   61      6
769   30   50   24   46   96      6

[770 rows x 6 columns]


In [54]:
print("Pig")
print(Output7)

Pig
       0    1    2    3    4  Class
0     70   63   61  141   82      7
1    195  360  409  102  203      7
2    309  317  319  323  324      7
3    102   78   73  164   92      7
4    254  496  402  194  254      7
..   ...  ...  ...  ...  ...    ...
185  243  242  288  257  219      7
186   75   66   67   98   55      7
187   81   60   66  106  108      7
188   92  132   87  234  112      7
189  277  173  256  230  312      7

[190 rows x 6 columns]


In [55]:
print("Rabbit")
print(Output8)

Rabbit
       0    1    2    3    4  Class
0     54  171   62   68   56      8
1     21   54   38   47   20      8
2     42   38   42   46   46      8
3    304  144  225  167  290      8
4    540    4  112  135  441      8
..   ...  ...  ...  ...  ...    ...
210  211  249   89  147  183      8
211  140  110   63  105  125      8
212   12   32   33    6   18      8
213   95  168   52   68   92      8
214  300  175  251  248  316      8

[215 rows x 6 columns]


In [56]:
print("Sheep")
print(Output9)

Sheep
      0    1    2    3    4  Class
0   278  122  236  171  201      9
1   269  193  273  256  302      9
2   160  215  136   84   86      9
3   186  242  188  320  234      9
4    32   65   71  107   46      9
..  ...  ...  ...  ...  ...    ...
94  238  218  270   82   97      9
95  111  136   96  200  168      9
96  115  148   86  161  125      9
97  146  214  100  418  360      9
98  183  205  279  215  130      9

[99 rows x 6 columns]


In [57]:
A = pd.concat([Output1, Output2, Output3,Output4,Output5,Output6,Output7,Output8,Output9], ignore_index=True)
A

0    1    2    3    4  Class
0      50   76   65   58   37      1
1      75  237  128  157  120      1
2     148  236  138  158  106      1
3      93  275  190  194  160      1
4     179  209  103  152   83      1
...   ...  ...  ...  ...  ...    ...
2064  238  218  270   82   97      9
2065  111  136   96  200  168      9
2066  115  148   86  161  125      9
2067  146  214  100  418  360      9
2068  183  205  279  215  130      9

[2069 rows x 6 columns]

In [58]:
csv_data=A.to_csv(r'D:/cv_final_project\z\Final_SIFT\FinalSIFT.csv', mode='a',header=False,index=False)


In [59]:
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, f1_score

In [60]:
Data_SIFT=A
Data_SIFT
df = pd.DataFrame(Data_SIFT)
print("Completed")

Completed


In [61]:
csv_data=df.to_csv(r'D:/cv_final_project\z\Final_SIFT\FinalFusedSIFT.csv', mode='a',header=False,index=False)

In [62]:
reduced_features = pd.read_csv(r'D:/cv_final_project\z\Final_SIFT\FinalFusedSIFT.csv',header=None)
reduced_features

0    1    2    3    4  5
0      37   65   76   50   58  1
1     120  128  237   75  157  1
2     106  138  236  148  158  1
3     161  190  274   93  194  1
4      83  103  209  179  152  1
...   ...  ...  ...  ...  ... ..
4133  238  218  270   82   97  9
4134  111  136   96  200  168  9
4135  115  148   86  161  125  9
4136  146  214  100  418  360  9
4137  183  205  279  215  130  9

[4138 rows x 6 columns]

In [63]:
reduced_features.isnull().values.any()
X = reduced_features.drop(columns= 5, axis=1)
Y = reduced_features[5]

In [64]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.2, random_state = 0)
# describes info about train and test set
print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", Y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", Y_test.shape)

Number transactions X_train dataset:  (3310, 5)
Number transactions y_train dataset:  (3310,)
Number transactions X_test dataset:  (828, 5)
Number transactions y_test dataset:  (828,)


In [65]:
from sklearn.linear_model import LogisticRegression

# Create a Logistic Regression classifier
modelLR = LogisticRegression(max_iter=1000, random_state=42)
modelLR.fit(X_train, Y_train)


# Accuracy on training data
X_train_prediction = modelLR.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Train data: ', train_data_accuracy)
print('Precision:', precision_score(X_train_prediction, Y_train, average='weighted'))
print('Recall:', recall_score(X_train_prediction, Y_train, average='weighted'))
print('F1 score:', f1_score(X_train_prediction, Y_train, average='weighted'))
train_confusion_matrix = confusion_matrix(X_train_prediction, Y_train)
print("Confusion Matrix for Training Data:")
print(train_confusion_matrix)



# Accuracy on test data
X_test_prediction = modelLR.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test data: ', test_data_accuracy)
print('Precision:', precision_score(X_test_prediction, Y_test, average='weighted'))
print('Recall:', recall_score(X_test_prediction, Y_test, average='weighted'))
print('F1 score:', f1_score(X_test_prediction, Y_test, average='weighted'))
test_confusion_matrix = confusion_matrix(X_test_prediction, Y_test)
print("\nConfusion Matrix for Testing Data:")
print(test_confusion_matrix)

Accuracy on Train data:  0.4283987915407855
Precision: 0.8254180507370856
Recall: 0.4283987915407855
F1 score: 0.5330669951178412
Confusion Matrix for Training Data:
[[   0    0    0    0    0    1    0    0    0]
 [   0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0]
 [   3    9    8   96   19   15   11   11   15]
 [   1    0    0   12   28    5    9    3   10]
 [  48   98  213  506  137 1166  191  282  125]
 [  16    8   13   24   11   46  102   12    6]
 [   0    0   17    1    1    1    0   24    3]
 [   0    0    0    0    0    0    1    0    2]]

Accuracy on Test data:  0.43478260869565216
Precision: 0.8394371681065035
Recall: 0.43478260869565216
F1 score: 0.5388752177479859

Confusion Matrix for Testing Data:
[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   2   4  30   7   2   1   4   3]
 [  0   0   0   2   6   0   2   1   2]
 [ 20  23  49 122  34 292  39  84  32]

C:\Users\parth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\parth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\parth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create a Decision Tree Classifier
modelDT = DecisionTreeClassifier(max_depth=9)

# Train the model on the training data
modelDT.fit(X_train, Y_train)

# Predict on the training data
X_train_prediction = modelDT.predict(X_train)

# Calculate accuracy on training data
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training Data: ', train_data_accuracy)

# Calculate precision on training data
train_data_precision = precision_score(X_train_prediction, Y_train, average='weighted')
print('Precision on Training Data: ', train_data_precision)

# Calculate recall on training data
train_data_recall = recall_score(X_train_prediction, Y_train, average='weighted')
print('Recall on Training Data: ', train_data_recall)

# Calculate F1 score on training data
train_data_f1_score = f1_score(X_train_prediction, Y_train, average='weighted')
print('F1 Score on Training Data: ', train_data_f1_score)

# Generate a confusion matrix for training data
confusion_matrix_train = confusion_matrix(Y_train, X_train_prediction)
print('Confusion Matrix (Training Data):\n', confusion_matrix_train)

# Predict on the test data
X_test_prediction = modelDT.predict(X_test)

# Calculate accuracy on test data
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test Data: ', test_data_accuracy)

# Calculate precision on test data
test_data_precision = precision_score(X_test_prediction, Y_test, average='weighted')
print('Precision on Test Data: ', test_data_precision)

# Calculate recall on test data
test_data_recall = recall_score(X_test_prediction, Y_test, average='weighted')
print('Recall on Test Data: ', test_data_recall)

# Calculate F1 score on test data
test_data_f1_score = f1_score(X_test_prediction, Y_test, average='weighted')
print('F1 Score on Test Data: ', test_data_f1_score)

# Generate a confusion matrix for test data
confusion_matrix_test = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix (Test Data):\n', confusion_matrix_test)


Accuracy on Training Data:  0.6229607250755287
Precision on Training Data:  0.704068277990048
Recall on Training Data:  0.6229607250755287
F1 Score on Training Data:  0.64265830802149
Confusion Matrix (Training Data):
 [[  23    0    4   12    0   16    7    5    1]
 [   0   27    9   24    0   53    1    1    0]
 [   0    1  132   16    5   70    9   18    0]
 [   1    1   29  342    3  225    7   29    2]
 [   0    2    8   16   77   83    7    2    1]
 [   1    2   25   60    5 1096   17   27    1]
 [   0    0   15   31    2   73  165   25    3]
 [   0    1   12   43    6  104    6  158    2]
 [   0    5    6   33    8   52    9    6   42]]

Accuracy on Test Data:  0.4722222222222222
Precision on Test Data:  0.5620279816755633
Recall on Test Data:  0.4722222222222222
F1 Score on Test Data:  0.5053525920415871
Confusion Matrix (Test Data):
 [[  0   1   0   2   2   9   4   7   1]
 [  0   3   2   8   0  11   0   1   0]
 [  0   2  14   5   0  23   5   9   1]
 [  0   0  11  62   3  68   

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create a Random Forest Classifier
modelRF = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training data
modelRF.fit(X_train, Y_train)

# Predict on the training data
X_train_prediction = modelRF.predict(X_train)

# Calculate accuracy on training data
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training Data: ', train_data_accuracy)

# Calculate precision on training data
train_data_precision = precision_score(X_train_prediction, Y_train, average='weighted')
print('Precision on Training Data: ', train_data_precision)

# Calculate recall on training data
train_data_recall = recall_score(X_train_prediction, Y_train, average='weighted')
print('Recall on Training Data: ', train_data_recall)

# Calculate F1 score on training data
train_data_f1_score = f1_score(X_train_prediction, Y_train, average='weighted')
print('F1 Score on Training Data: ', train_data_f1_score)

# Generate a confusion matrix for training data
confusion_matrix_train = confusion_matrix(Y_train, X_train_prediction)
print('Confusion Matrix (Training Data):\n', confusion_matrix_train)

# Predict on the test data
X_test_prediction = modelRF.predict(X_test)

# Calculate accuracy on test data
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test Data: ', test_data_accuracy)

# Calculate precision on test data
test_data_precision = precision_score(X_test_prediction, Y_test, average='weighted')
print('Precision on Test Data: ', test_data_precision)

# Calculate recall on test data
test_data_recall = recall_score(X_test_prediction, Y_test, average='weighted')
print('Recall on Test Data: ', test_data_recall)

# Calculate F1 score on test data
test_data_f1_score = f1_score(X_test_prediction, Y_test, average='weighted')
print('F1 Score on Test Data: ', test_data_f1_score)

# Generate a confusion matrix for test data
confusion_matrix_test = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix (Test Data):\n', confusion_matrix_test)


Accuracy on Training Data:  1.0
Precision on Training Data:  1.0
Recall on Training Data:  1.0
F1 Score on Training Data:  1.0
Confusion Matrix (Training Data):
 [[  68    0    0    0    0    0    0    0    0]
 [   0  115    0    0    0    0    0    0    0]
 [   0    0  251    0    0    0    0    0    0]
 [   0    0    0  639    0    0    0    0    0]
 [   0    0    0    0  196    0    0    0    0]
 [   0    0    0    0    0 1234    0    0    0]
 [   0    0    0    0    0    0  314    0    0]
 [   0    0    0    0    0    0    0  332    0]
 [   0    0    0    0    0    0    0    0  161]]

Accuracy on Test Data:  0.5301932367149759
Precision on Test Data:  0.6366884147357121
Recall on Test Data:  0.5301932367149759
F1 Score on Test Data:  0.5634893136612398
Confusion Matrix (Test Data):
 [[  2   0   0   4   1  11   6   1   1]
 [  0   6   0   9   0   8   0   1   1]
 [  0   0  19   8   0  21   3   7   1]
 [  1   1   5  65   3  71   6   7   2]
 [  1   0   1   8  10  24   5   0   1]
 [  0  

In [68]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Create an SVM classifier with a linear kernel
modelSVM = SVC(kernel='linear')

# Train the model on the training data
modelSVM.fit(X_train, Y_train)

# Predict on the training data
X_train_prediction = modelSVM.predict(X_train)

# Calculate accuracy on training data
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training Data: ', train_data_accuracy)

# Calculate precision on training data
train_data_precision = precision_score(X_train_prediction, Y_train, average='weighted')
print('Precision on Training Data: ', train_data_precision)

# Calculate recall on training data
train_data_recall = recall_score(X_train_prediction, Y_train, average='weighted')
print('Recall on Training Data: ', train_data_recall)

# Calculate F1 score on training data
train_data_f1_score = f1_score(X_train_prediction, Y_train, average='weighted')
print('F1 Score on Training Data: ', train_data_f1_score)

# Generate a confusion matrix for training data
confusion_matrix_train = confusion_matrix(Y_train, X_train_prediction)
print('Confusion Matrix (Training Data):\n', confusion_matrix_train)

# Predict on the test data
X_test_prediction = modelSVM.predict(X_test)

# Calculate accuracy on test data
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('\nAccuracy on Test Data: ', test_data_accuracy)

# Calculate precision on test data
test_data_precision = precision_score(X_test_prediction, Y_test, average='weighted')
print('Precision on Test Data: ', test_data_precision)

# Calculate recall on test data
test_data_recall = recall_score(X_test_prediction, Y_test, average='weighted')
print('Recall on Test Data: ', test_data_recall)

# Calculate F1 score on test data
test_data_f1_score = f1_score(X_test_prediction, Y_test, average='weighted')
print('F1 Score on Test Data: ', test_data_f1_score)

# Generate a confusion matrix for test data
confusion_matrix_test = confusion_matrix(Y_test, X_test_prediction)
print('Confusion Matrix (Test Data):\n', confusion_matrix_test)

Accuracy on Training Data:  0.4253776435045317
Precision on Training Data:  0.8829578032717132
Recall on Training Data:  0.4253776435045317
F1 Score on Training Data:  0.547245972902218
Confusion Matrix (Training Data):
 [[   0    0    0    3    1   47   17    0    0]
 [   0    0    0    7    0   95   13    0    0]
 [   0    0    0    9    0  223   19    0    0]
 [   0    0    0   80    5  538   16    0    0]
 [   0    0    0   24   23  143    6    0    0]
 [   0    0    0    5    4 1208   17    0    0]
 [   0    0    0    6   12  199   97    0    0]
 [   0    0    0   19    1  303    9    0    0]
 [   0    0    0   11    7  140    3    0    0]]

Accuracy on Test Data:  0.42632850241545894
Precision on Test Data:  0.8908135489593291
Recall on Test Data:  0.42632850241545894
F1 Score on Test Data:  0.549103867196541
Confusion Matrix (Test Data):
 [[  0   0   0   1   0  20   5   0   0]
 [  0   0   0   4   0  20   1   0   0]
 [  0   0   0   3   0  53   3   0   0]
 [  0   0   0  21   2 134

C:\Users\parth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\parth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
